name: All

on: [push]

env:
  project_name: "me_favorite_reels"
  python_version: "3.10"


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: 🐍 Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        source venv/bin/activate
        pylint app -r n
        deactivate
